// Generated by CoffeeScript 1.4.0
(function() {
  var Router, argv, clean_up, http, router, server;

  Router = require('node-simple-router');

  http = require('http');

  argv = process.argv.slice(2);

  router = Router({
    static_route: process.cwd(),
    served_by: "Guaycuru Web Server",
    version: '0.1.2',
    cgi_dir: argv[1] || 'cgi-bin',
    software_name: 'guaycuru',
    use_nsr_session: false
  });

  argv = process.argv.slice(2);

  server = http.createServer(router);

  server.on('listening', function() {
    var addr;
    addr = server.address() || {
      address: '0.0.0.0',
      port: argv[0] || 8000
    };
    router.log("Serving web content at " + addr.address + ":" + addr.port + " - PID: " + process.pid);
    return router.log("Working directory: " + router.static_route);
  });

  clean_up = function() {
    router.log(' ');
    router.log("Server shutting up...");
    router.log(' ');
    server.close();
    return process.exit(0);
  };

  process.on('SIGINT', clean_up);

  process.on('SIGHUP', clean_up);

  process.on('SIGQUIT', clean_up);

  process.on('SIGTERM', clean_up);

  server.listen((argv[0] != null) && !isNaN(parseInt(argv[0])) ? parseInt(argv[0]) : 8000);

}).call(this);
