// Generated by CoffeeScript 1.4.0
(function() {
  var Router, argv, http, router, server;

  Router = require('node-simple-router');

  http = require('http');

  argv = process.argv.slice(2);

  router = Router({
    static_route: process.cwd(),
    served_by: "Guaycuru Web Server",
    version: '0.0.6',
    cgi_dir: argv[1] || 'cgi-bin'
  });

  server = http.createServer(router);

  server.on('listening', function() {
    var addr;
    addr = server.address() || {
      address: '0.0.0.0',
      port: argv[0] || 8000
    };
    router.log("Serving web content at " + addr.address + ":" + addr.port);
    return router.log("Working directory: " + router.static_route);
  });

  process.on("SIGINT", function() {
    server.close();
    router.log("\n Server shutting up...\n");
    return process.exit(0);
  });

  server.listen((argv[0] != null) && !isNaN(parseInt(argv[0])) ? parseInt(argv[0]) : 8000);

}).call(this);
