// Generated by CoffeeScript 1.3.1
(function() {
  var Router, addr, argv, http, router, server, spawn;

  Router = require('node-simple-router');

  http = require('http');

  spawn = require('child_process').spawn;

  argv = process.argv.slice(2);

  router = Router({
    static_route: process.cwd(),
    served_by: "Guaycuru Web Server",
    version: '0.0.2',
    cgi_dir: argv[1] || 'cgi-bin'
  });

  router._500 = function(req, res, path, message) {
    res.writeHead(500, {
      'Content-Type': 'text/html'
    });
    return res.end("<h2>500 - Resource " + path + ": " + message + "</h2>\n<hr/><h3>Served by " + router.served_by + " v" + router.version + "</h3>\n<p style=\"text-align: center;\"><button onclick='history.back();'>Back</button></p>");
  };

  router.old_static = router["static"];

  router["static"] = function(pathname, res) {
    var child, full_path;
    if (pathname.indexOf("" + router.cgi_dir + "/") !== -1) {
      try {
        full_path = "" + router.static_route + pathname;
        child = spawn(full_path);
        res.writeHead(200, {
          'Content-type': 'text/html'
        });
        child.stdout.on('data', function(data) {
          return res.write(data);
        });
        return child.on('exit', function() {
          return res.end();
        });
      } catch (error) {
        return router._500(null, res, pathname, error.toString());
      }
    } else {
      return router.old_static(pathname, res);
    }
  };

  router.log("Working directory: " + router.static_route);

  server = http.createServer(router);

  server.listen((argv[0] != null) && !isNaN(parseInt(argv[0])) ? parseInt(argv[0]) : 8000);

  addr = (server != null ? server.address() : void 0) || {
    address: '0.0.0.0',
    port: argv[0] || 8000
  };

  router.log("Serving web content at " + addr.address + ":" + addr.port);

  process.on("SIGINT", function() {
    server.close();
    router.log("\n Server shutting up...\n");
    return process.exit(0);
  });

}).call(this);
